### ISSUE TITLE
Facebook sharer url breaks

### ISSUE THREAD

**Issue by angelgbi** [nicolasbeauvais/vue-social-sharing#123]
Hi guys. Currently I'm implementing the vue-social-sharing component on a project with Nuxt. My problem is if I don't set any hashtags, the facebook sharer url breaks. Have you test this?

**Comment by nicolasbeauvais** [comment]
Hello @angelgbi,

this bug should be fixed in the last [v2.4.0](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.4.0) release.

Feel free to re-open this issue if you still experience the bug.

**Comment by angelgbi** [comment]
Hi, I just tested the new version. But the issue persist!

**Comment by dylankelly** [comment]
Hi @nicolasbeauvais, the fix you on implemented at https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/src/social-sharing.js#L171 adds a `#` for blank hashtags. I've added a PR which does a simple check for hashtag length.

**Comment by nicolasbeauvais** [comment]
The fix is merged and tagged, thank you again @dylankelly. @angelgbi Let me know if it works as expected now :smile:

**Comment by dylankelly** [comment]
Cheers thanks for your library @nicolasbeauvais !

**Comment by dylankelly** [comment]
Hmm looks like it didn't get built though? https://github.com/nicolasbeauvais/vue-social-sharing/blob/master/dist/vue-social-sharing.common.js#L248 Is still the same as 2.4.0?

**Comment by nicolasbeauvais** [comment]
My bad :disappointed:, it should be fixed now!
